name: Auto update base_registry geojson
on:
  schedule:
    - cron: "3/5 * * * *"

jobs:
  build:
    name: Update base registry geojson
    runs-on: ubuntu-latest
    steps:
      - name: Echo Scheduled Run
        run: echo "This is the start of the scheduled run"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build geojson
        run: npm run build-geojson
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          body: Update base registry geojson
